### ISSUE TITLE
PhidgetAPI does not work with node v0.10.40 but works with v0.12.7

### ISSUE THREAD

**Issue by rajivsavroop** [RIAEvangelist/node-phidget-API#10]
Object.observe method not defined on objects.

**Comment by RIAEvangelist** [comment]
We should find out what version of node started allowing object.observe

@mrvini do you think we should add a polyfill for backwards compatibility or require, at a minimum, the first version of node to support Object.observe?

**Comment by mrvini** [comment]
@RIAEvangelist , since the oldest node version that is supported is 0.10.40, that implies that the consumers will be lost if not using the polyfill, however the amount of people using this version shall be decreasing in the future, thus might not make sense to spend time on backwards compatibility. In addition to that, starting with version v0.11.6, in ES6, there is  a way to enable observer option, just run on your machine to see if that is available.

node --v8-options | grep harm

**Comment by RIAEvangelist** [comment]
@mrvini sounds like we should require a minimum node version of 12 yes?

**Comment by RIAEvangelist** [comment]
we now require v0.11.3 or **newer** for the latest releases.
