### ISSUE TITLE
Events not re-firing when reconnecting

### ISSUE THREAD

**Issue by MaybeRex** [RIAEvangelist/node-phidget-API#21]
```
   'connected'
```

and

```
   'phidgetReady'
```

are both not firing when reconnecting

**Comment by RIAEvangelist** [comment]
So I figured out why this is :

By design when the phidget is disconnected it is destroyed. If upon the disconnected event you were to automatically try phidget connect again, the next connected and phidget ready event would fire wh en they happened.

Perhaps though we should consider adding in a retry key in the connect object.

I think this might be more obvious and [KISS](https://en.wikipedia.org/wiki/KISS_principle) for other developers using the API. What do you think @MaybeRex ?

**Comment by MaybeRex** [comment]
I think this is a great idea for a few reasons. Instead of possibly overhauling the api and making changes that might cause further issues, a retry event would have a lot of transparency and I think it is very KISS

**Comment by RIAEvangelist** [comment]
OK, it's settled thats what we'll do.
