### ISSUE TITLE
document addListener and removeListener.

### ISSUE THREAD

**Issue by rajivsavroop** [RIAEvangelist/node-phidget-API#23]
add an "Off" method to unbind the events

**Comment by RIAEvangelist** [comment]
It seems this is a native EventEmitter

in the newest versions of node they have added the addListener instead of on which was the default in the past and still supported.

That being said the way to remove this is [removeListener](https://nodejs.org/api/events.html#events_emitter_removelistener_event_listener) check it out.

We do need to document addListener and removeListener though.

**Comment by RIAEvangelist** [comment]
closed by #25
